import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { reference } from '@keynv/core';
import { Command, Option } from 'clipanion';
import { ApiClient } from '../client/http.js';
import { parseEnvFile } from '../exec/envFile.js';
import { writeAiContext } from '../init/ai-context.js';
import { backupEnvFile } from '../init/backup.js';
import { type SourceEntry, planVaultKeys } from '../init/collision.js';
import {
  type EnvFileHit,
  findEnvFilesRecursive,
  findProjectRoot,
  suggestedEnvForSuffix,
} from '../init/detect.js';
import { classifyEntry } from '../init/heuristics.js';
import { composeKeynvEnv, runInitFlow } from '../ui/flows/init.js';
import { UserCancelled } from '../ui/helpers/cancel.js';
import { isInteractive } from '../ui/helpers/tty.js';
import { resolveProjectId } from './project.js';

/**
 * Normalise a raw env-var name to a vault alias key. Preserves the
 * original case when valid; falls back to lowercase + underscore→dash
 * for names that would otherwise fail KEY_RE validation.
 */
function toAliasKey(name: string): string {
  if (!name) return name;
  const KEY_RE = /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/;
  if (KEY_RE.test(name)) return name;
  const normalised = name.toLowerCase().replace(/_/g, '-');
  if (KEY_RE.test(normalised)) return normalised;
  return normalised.replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 64) || 'key';
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Render an env-file's path relative to the project root, with POSIX
 * separators, for stdout/stderr lines that mention specific files.
 */
function displayHit(rootPath: string, file: EnvFileHit): string {
  return relFromRootPath(rootPath, file.path);
}

/** Stable POSIX-style relative path used in logs. */
function relFromRootPath(rootPath: string, absPath: string): string {
  const r = relative(rootPath, absPath);
  if (r === '') return '.';
  return r.split(/[\\/]/).filter(Boolean).join('/');
}

/**
 * Default tier + approval choice for a freshly-created env. Matches
 * the helper in the interactive flow; duplicated here to avoid making
 * UI code depend on this command module (or vice versa).
 */
function envBodyFor(name: string): {
  name: string;
  tier: 'production' | 'non-production';
  require_approval: boolean;
} {
  const isProd = name === 'prod' || name === 'production';
  return {
    name,
    tier: isProd ? 'production' : 'non-production',
    require_approval: isProd,
  };
}

function writeKeynvEnvMappings(
  path: string,
  projectName: string,
  envName: string,
  secrets: Array<{ name: string; aliasKey: string }>,
): number {
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const lines: string[] = [];
  for (const s of secrets) {
    const hasEntry = new RegExp(`^${escapeRegExp(s.name)}=`, 'm').test(existing);
    if (!hasEntry) {
      lines.push(`# ${s.name}`, `${s.name}=@${projectName}.${envName}.${s.aliasKey}`);
    }
  }

  if (lines.length === 0) return 0;

  const prefix = existing.trimEnd();
  const block = `# Generated by keynv setup\n${lines.join('\n')}\n`;
  writeFileSync(path, prefix ? `${prefix}\n\n${block}` : block);
  return lines.length / 2;
}

export class InitCommand extends Command {
  static override paths = [['init']];
  static override usage = Command.Usage({
    description: 'Migrate an existing project from .env to keynv.',
    details: `
Walks the current directory's .env files, prompts you to mark which
keys are real secrets, uploads those to the keynv vault, writes a
.keynv.env file with alias references, and (optionally) wraps your
package.json scripts with \`keynv exec\`.

Safe to re-run: existing .keynv.env entries are preserved; new
entries are appended below a marker.

--dry-run prints the secrets that would be uploaded and the alias
mappings that would be written to .keynv.env, then exits without
touching any files or making any network calls. Use it to preview
what init will do before committing.

For scripted migration, use \`--env-file\` or \`--secret\` flags, or
\`--yes\` to auto-scan the project directory and set up without
any prompts.
`,
    examples: [
      ['Walk the current project', '$0 init'],
      ['Preview without writing or uploading', '$0 init --dry-run'],
      ['Skip the package.json script-wrapping step', '$0 init --no-scripts'],
      ['Non-interactive (CI/CD)', '$0 init --env-file .env --project myproject --env dev'],
      ['Auto-scan & set up without prompts (CI/CD)', '$0 init --yes'],
    ],
  });

  dryRun = Option.Boolean('--dry-run', false, {
    description:
      'Scan .env files and print the secrets that would be uploaded and the alias mappings that would be written — no files written, no vault calls made.',
  });
  noScripts = Option.Boolean('--no-scripts', false, {
    description: 'Skip the package.json script-wrapping step.',
  });
  envFile = Option.String('--env-file', {
    description: 'Path to .env file to migrate (non-interactive mode).',
  });
  project = Option.String('--project', {
    description: 'Project name or ID (non-interactive mode).',
  });
  env = Option.String('--env', {
    description: 'Environment name for --env-file (default: dev).',
  });
  secret = Option.Array('--secret', {
    description: 'KEY=value secret to upload (non-interactive). Can be specified multiple times.',
  });
  yes = Option.Boolean('--yes', false, {
    description:
      'Auto-scan .env files, classify, and set up without prompts. Implies non-interactive mode.',
  });

  async execute(): Promise<number> {
    const client = new ApiClient();
    await client.ensureHydrated();
    if (!client.isLoggedIn) {
      this.context.stderr.write('keynv: not connected. Run `keynv` first.\n');
      return 1;
    }

    const hasEnvFile = this.envFile != null;
    const hasSecrets = this.secret != null && this.secret.length > 0;
    const isNonInteractive = hasEnvFile || hasSecrets || this.dryRun || this.yes;

    if (isNonInteractive) {
      return this.runNonInteractive(client);
    }

    if (!isInteractive()) {
      this.context.stderr.write(
        'keynv init requires an interactive terminal. Use --dry-run, --env-file, or --secret for scripted setup.\n',
      );
      return 1;
    }

    try {
      const outcome = await runInitFlow(client, {
        cwd: process.cwd(),
        dryRun: this.dryRun,
        noScripts: this.noScripts,
      });
      return outcome.exitCode;
    } catch (err) {
      if (err instanceof UserCancelled) return 130;
      const e = err as { code?: string; message: string; status?: number };
      this.context.stderr.write(`keynv: ${e.message}\n`);
      return 1;
    }
  }

  async runNonInteractive(client: ApiClient): Promise<number> {
    // If --yes and no explicit --env-file/--secret, auto-scan the
    // project directory for .env files.
    if (this.yes && !this.envFile && !this.secret) {
      return this.runAutoScan(client);
    }

    const projectName = this.project;
    if (!projectName) {
      this.context.stderr.write('keynv: --project is required in non-interactive mode.\n');
      return 1;
    }

    const resolved = await resolveProjectId(client, projectName);
    if (!resolved) {
      this.context.stderr.write(`keynv: project not found: ${projectName}\n`);
      return 1;
    }
    const projectId = resolved;

    const envName = this.env ?? 'dev';
    const secrets: Array<{ name: string; value: string }> = [];

    if (this.envFile) {
      try {
        const content = readFileSync(this.envFile, 'utf8');
        const entries = parseEnvFile(content, this.envFile);
        for (const e of entries) {
          if (classifyEntry(e.name, e.value).verdict === 'secret') {
            secrets.push({ name: e.name, value: e.value });
          }
        }
      } catch (err) {
        this.context.stderr.write(
          `keynv: cannot read ${this.envFile}: ${err instanceof Error ? err.message : String(err)}\n`,
        );
        return 1;
      }
    }

    if (this.secret) {
      for (const spec of this.secret) {
        const eq = spec.indexOf('=');
        if (eq <= 0) {
          this.context.stderr.write(`keynv: invalid --secret '${spec}', expected KEY=value\n`);
          return 1;
        }
        const name = spec.slice(0, eq);
        const value = spec.slice(eq + 1);
        secrets.push({ name, value });
      }
    }

    if (secrets.length === 0) {
      this.context.stdout.write('keynv: nothing to migrate.\n');
      return 0;
    }

    if (this.dryRun) {
      if (this.envFile || (this.secret && this.secret.length > 0)) {
        this.context.stdout.write(
          `keynv: dry-run — would upload ${secrets.length} secret(s) to project ${projectName} (${projectId}) in env ${envName}\n`,
        );
        for (const { name } of secrets) {
          const aliasKey = toAliasKey(name);
          this.context.stdout.write(`  ${name}=@${projectName}.${envName}.${aliasKey}\n`);
        }
        return 0;
      }
      this.context.stdout.write(
        'keynv: dry-run mode — no --env-file or --secret provided. Nothing to scan.\n',
      );
      return 0;
    }

    const secretsWithKeys = secrets.map((s) => ({ ...s, aliasKey: toAliasKey(s.name) }));
    const result = await this.uploadSecrets(
      client,
      projectId,
      projectName,
      envName,
      secretsWithKeys,
    );
    if (result !== 0) return result;

    const keynvEnvPath = join(process.cwd(), '.keynv.env');
    const written = writeKeynvEnvMappings(keynvEnvPath, projectName, envName, secretsWithKeys);
    this.context.stdout.write(
      written > 0
        ? `keynv: wrote ${keynvEnvPath}\n`
        : `keynv: ${keynvEnvPath} already up to date\n`,
    );
    return 0;
  }

  /**
   * Auto-scan mode (--yes without explicit --env-file). Recursively
   * finds .env files across the project (root, apps/*, packages/*, …),
   * classifies entries, creates the project + needed envs, uploads
   * secrets, writes a `.keynv.env` next to each source `.env`, and
   * renames the originals to `.env.backup` — all without prompts.
   *
   * Multi-source key collisions are resolved by auto-prefixing the
   * vault key with the source directory slug; the user's code keeps
   * using the original env-var name locally.
   */
  async runAutoScan(client: ApiClient): Promise<number> {
    const root = findProjectRoot(process.cwd());
    if (!root) {
      this.context.stderr.write('keynv: no project root found (no package.json, .git, etc.).\n');
      return 1;
    }

    const envFiles = findEnvFilesRecursive(root.path);
    if (envFiles.length === 0) {
      this.context.stdout.write(
        'keynv: no .env files found (scanned root and subdirectories). Nothing to migrate.\n',
      );
      return 0;
    }

    const projectName = this.project ?? root.suggestedName;

    // Parse every file, classify per-entry, build SourceEntry list. Each
    // file gets its own keynv env from its filename suffix (or --env override).
    // Both secret-class and literal-class entries are kept (literals pass
    // through into the `.keynv.env` unchanged so the app keeps working);
    // only framework/shell-managed entries (NODE_ENV, PORT, …) are filtered.
    const cliEnv = this.env;
    const allSources: SourceEntry[] = [];
    const isSecret = new Set<string>(); // composite `${file.path}|${name}`
    let skippedCount = 0;
    for (const f of envFiles) {
      try {
        const entries = parseEnvFile(readFileSync(f.path, 'utf8'), f.path);
        const envName = cliEnv ?? suggestedEnvForSuffix(f.suffix);
        for (const e of entries) {
          const verdict = classifyEntry(e.name, e.value).verdict;
          if (verdict === 'skip') {
            skippedCount++;
            continue;
          }
          if (verdict === 'secret' && !e.isAlias) {
            isSecret.add(`${f.path}|${e.name}`);
          }
          allSources.push({
            file: f,
            envName,
            name: e.name,
            value: e.value,
            isAlias: e.isAlias,
            line: e.line,
          });
        }
      } catch {
        this.context.stderr.write(
          `keynv: warning — could not parse ${displayHit(root.path, f)}, skipping.\n`,
        );
      }
    }

    if (allSources.length === 0) {
      this.context.stdout.write('keynv: no migrable entries in .env files. Nothing to do.\n');
      return 0;
    }

    const plan = planVaultKeys(allSources);
    for (const r of plan.renamed) {
      this.context.stderr.write(
        `keynv: renamed ${r.localKey} -> ${r.vaultKey} in env ${r.envName} (collision with ${r.otherSources.map((s) => displayHit(root.path, s)).join(', ')})\n`,
      );
    }
    for (const m of plan.merged) {
      this.context.stderr.write(
        `keynv: merged ${m.key} in env ${m.envName} (same value in ${m.sources.map((s) => displayHit(root.path, s)).join(', ')})\n`,
      );
    }
    for (const s of plan.shadowed) {
      this.context.stderr.write(
        `keynv: dotenv last-wins: ${s.localKey} in ${relFromRootPath(root.path, s.containingDir)} (${s.earlierFiles.join(', ')} -> ${s.laterFile})\n`,
      );
    }

    const distinctEnvs = [...new Set(plan.resolved.map((r) => r.envName))];
    const secretCount = plan.resolved.filter((r) =>
      isSecret.has(`${r.source.path}|${r.localKey}`),
    ).length;
    const literalCount = plan.resolved.length - secretCount;
    this.context.stdout.write(
      `keynv: auto-scan found ${secretCount} secret(s) and ${literalCount} literal(s) across ${envFiles.length} file(s)${skippedCount > 0 ? `; skipped ${skippedCount} framework entr${skippedCount === 1 ? 'y' : 'ies'}` : ''}.\n`,
    );

    if (this.dryRun) {
      for (const r of plan.resolved) {
        const tag = isSecret.has(`${r.source.path}|${r.localKey}`) ? 'secret' : 'literal';
        const target = isSecret.has(`${r.source.path}|${r.localKey}`)
          ? `@${projectName}.${r.envName}.${r.vaultKey}`
          : r.value;
        this.context.stdout.write(
          `  ${displayHit(root.path, r.source)}: ${r.localKey}=${target}  [${tag}]\n`,
        );
      }
      return 0;
    }

    // Resolve or create the project, with all distinct envs.
    let projectId: string;
    try {
      projectId = await resolveProjectId(client, projectName);
      // Existing project: make sure each env we need exists.
      try {
        const detail = await client.request<{
          environments: Array<{ name: string }>;
        }>(`/v1/projects/${projectId}`);
        const existing = new Set(detail.environments.map((e) => e.name));
        const missing = distinctEnvs.filter((e) => !existing.has(e));
        for (const env of missing) {
          await client.request(`/v1/projects/${projectId}/environments`, {
            method: 'POST',
            body: envBodyFor(env),
          });
          this.context.stdout.write(`keynv: added env "${env}" to project "${projectName}".\n`);
        }
      } catch (err) {
        this.context.stderr.write(
          `keynv: warning — could not reconcile envs for ${projectName}: ${err instanceof Error ? err.message : String(err)}\n`,
        );
      }
    } catch {
      const created = await client.request<{ id: string; name: string }>('/v1/projects', {
        method: 'POST',
        body: {
          name: projectName,
          environments: distinctEnvs.map((name) => envBodyFor(name)),
        },
      });
      projectId = created.id;
      this.context.stdout.write(
        `keynv: created project "${projectName}" (${projectId}) with env(s): ${distinctEnvs.join(', ')}\n`,
      );
    }

    // Upload — one POST per unique (env, vaultKey) whose group contains
    // at least one secret-classified source. Literal-only groups stay
    // out of the vault.
    const aliasByGroup = new Map<string, string>();
    interface Group {
      envName: string;
      vaultKey: string;
      value: string;
    }
    const secretGroupMap = new Map<string, Group>();
    for (const r of plan.resolved) {
      if (!isSecret.has(`${r.source.path}|${r.localKey}`)) continue;
      const k = `${r.envName}|${r.vaultKey}`;
      if (!secretGroupMap.has(k)) {
        secretGroupMap.set(k, { envName: r.envName, vaultKey: r.vaultKey, value: r.value });
      }
    }

    let uploaded = 0;
    const failed: Array<{ name: string; reason: string }> = [];
    for (const [composite, g] of secretGroupMap) {
      const alias = reference.buildAlias({
        project: projectName,
        environment: g.envName,
        key: g.vaultKey,
      });
      if (!alias) {
        failed.push({ name: g.vaultKey, reason: `invalid alias key: ${g.vaultKey}` });
        continue;
      }
      try {
        await client.request(`/v1/projects/${projectId}/secrets`, {
          method: 'POST',
          body: { env: g.envName, key: g.vaultKey, value: g.value },
        });
        aliasByGroup.set(composite, alias.literal);
        uploaded++;
      } catch (err) {
        failed.push({
          name: g.vaultKey,
          reason: err instanceof Error ? err.message : String(err),
        });
      }
    }
    this.context.stdout.write(
      `keynv: uploaded ${uploaded}/${secretGroupMap.size} secret(s) to ${projectName}.\n`,
    );
    if (failed.length > 0) {
      for (const f of failed) this.context.stderr.write(`  failed: ${f.name} — ${f.reason}\n`);
      return 1;
    }

    // Pick a default env for the bare `.keynv.env` filename (others get `.keynv.<env>.env`).
    const defaultEnv = distinctEnvs.includes('dev') ? 'dev' : (distinctEnvs[0] as string);

    // Group resolved entries by (containingDir, env) and write a file per group.
    // Secret entries land as alias references; literals pass through unchanged.
    interface DirEnvBucket {
      containingDir: string;
      envName: string;
      aliasLines: Array<[string, string]>;
      literalEntries: Array<{ name: string; value: string }>;
    }
    const buckets = new Map<string, DirEnvBucket>();
    for (const r of plan.resolved) {
      const k = `${r.source.containingDir}|${r.envName}`;
      let b = buckets.get(k);
      if (!b) {
        b = {
          containingDir: r.source.containingDir,
          envName: r.envName,
          aliasLines: [],
          literalEntries: [],
        };
        buckets.set(k, b);
      }
      const isSec = isSecret.has(`${r.source.path}|${r.localKey}`);
      const alias = aliasByGroup.get(`${r.envName}|${r.vaultKey}`);
      if (isSec && alias !== undefined) {
        b.aliasLines.push([r.localKey, alias]);
      } else {
        b.literalEntries.push({ name: r.localKey, value: r.value });
      }
    }
    for (const b of buckets.values()) {
      const targetName = b.envName === defaultEnv ? '.keynv.env' : `.keynv.${b.envName}.env`;
      const targetPath = join(b.containingDir, targetName);
      const dirIntoExisting = existsSync(targetPath);
      const lines = composeKeynvEnv({
        uploadedAliases: new Map(b.aliasLines),
        literals: b.literalEntries,
        mergeWithExisting: dirIntoExisting ? readFileSync(targetPath, 'utf8') : null,
      });
      writeFileSync(targetPath, `${lines.join('\n')}\n`);
      this.context.stdout.write(
        `keynv: ${dirIntoExisting ? 'updated' : 'wrote'} ${relFromRootPath(root.path, targetPath)}\n`,
      );
    }

    // AGENTS.md (at project root) — best effort.
    try {
      const outcome = writeAiContext(root.path);
      if (outcome === 'created') this.context.stdout.write('keynv: wrote AGENTS.md\n');
    } catch {
      this.context.stdout.write('keynv: warning — could not write AGENTS.md.\n');
    }

    // Rename original .env files to .env.backup.
    for (const f of envFiles) {
      const relSrc = displayHit(root.path, f);
      try {
        const { renamedTo } = backupEnvFile(f.path);
        this.context.stdout.write(
          `keynv: renamed ${relSrc} -> ${relFromRootPath(root.path, renamedTo)}\n`,
        );
      } catch (err) {
        this.context.stderr.write(
          `keynv: warning — could not rename ${relSrc}: ${err instanceof Error ? err.message : String(err)}\n`,
        );
      }
    }

    this.context.stdout.write(
      'keynv: done. Use `keynv exec` to run commands with resolved secrets.\n',
    );
    return 0;
  }

  /**
   * Upload secrets to the vault and print the result. Shared between
   * runNonInteractive and runAutoScan.
   */
  async uploadSecrets(
    client: ApiClient,
    projectId: string,
    projectName: string,
    envName: string,
    secrets: Array<{ name: string; value: string; aliasKey: string }>,
  ): Promise<number> {
    let uploaded = 0;
    const failed: Array<{ name: string; reason: string }> = [];
    for (const s of secrets) {
      const alias = reference.buildAlias({
        project: projectName,
        environment: envName,
        key: s.aliasKey,
      });
      if (!alias) {
        failed.push({ name: s.name, reason: `invalid alias key: ${s.aliasKey}` });
        continue;
      }
      try {
        await client.request(`/v1/projects/${projectId}/secrets`, {
          method: 'POST',
          body: { env: envName, key: s.aliasKey, value: s.value },
        });
        uploaded++;
      } catch (err) {
        failed.push({ name: s.name, reason: err instanceof Error ? err.message : String(err) });
      }
    }
    this.context.stdout.write(
      `keynv: uploaded ${uploaded}/${secrets.length} secret(s) to ${projectName}.${envName}\n`,
    );
    if (failed.length > 0) {
      for (const f of failed) this.context.stderr.write(`  failed: ${f.name} — ${f.reason}\n`);
      return 1;
    }
    return 0;
  }
}
