import { randomBytes } from 'node:crypto';
import { Command, Option } from 'clipanion';

function generateSecret(bytes = 32): string {
  return randomBytes(bytes).toString('base64');
}

export class ServerInitCommand extends Command {
  static override paths = [['server', 'init']];
  static override usage = Command.Usage({
    description: 'Generate secrets and deployment files for a new keynv server.',
    details: `
Interactive onboarding wizard that generates the configuration
a fresh keynv server needs: JWT signing secret, master encryption
key, and deployment templates.

Outputs:
  • A .keynv-server.env file you feed into your deployment
    (Docker Compose, Coolify, or bare-metal).
  • Optionally a docker-compose.yml in the current directory.

Non-interactive with --yes to skip prompts.
`,
    examples: [
      ['Interactive wizard', '$0 server init'],
      ['Non-interactive (CI/scripts)', '$0 server init --yes'],
      ['Docker Compose output', '$0 server init --compose'],
      ['Custom output path', '$0 server init --out ./config/env'],
    ],
  });

  yes = Option.Boolean('--yes', false, {
    description: 'Skip all prompts (non-interactive).',
  });
  compose = Option.Boolean('--compose', false, {
    description: 'Also write a docker-compose.yml to the current directory.',
  });
  out = Option.String('--out', {
    description: 'Write server env file to this path (default: .keynv-server.env).',
  });

  async execute(): Promise<number> {
    const jwtSecret = generateSecret(48);
    const masterKey = generateSecret(32);
    const webSessionSecret = generateSecret(48);

    const outPath = this.out ?? '.keynv-server.env';
    const contents = [
      '# Generated by `keynv server init`.',
      '# Keep this file secret — it contains cryptographic key material.',
      `KEYNV_JWT_SECRET=${jwtSecret}`,
      `KEYNV_MASTER_KEY=${masterKey}`,
      '',
      '# Web dashboard session secret (required for Next.js JWE session tokens).',
      `KEYNV_WEB_SESSION_SECRET=${webSessionSecret}`,
      '',
      '# Server configuration (uncomment and adjust):',
      '# KEYNV_PORT=8080',
      '# KEYNV_WEB_URL=https://keynv.example.com',
      '# KEYNV_PUBLIC_REGISTRATION=false',
      '# KEYNV_DB_PATH=./keynv.db',
      '# KEYNV_MASTER_KEY_FILE=./master.key',
      '# KEYNV_RATE_LIMIT_PER_MINUTE=120',
      '# KEYNV_ARGON2_MEMORY_KIB=46080',
      '# KEYNV_ARGON2_TIME_COST=3',
    ].join('\n');

    const { writeFileSync } = await import('node:fs');
    writeFileSync(outPath, `${contents}\n`, { mode: 0o600 });

    this.context.stdout.write(`Wrote ${outPath}\n\n`);
    this.context.stdout.write('Generated secrets:\n');
    this.context.stdout.write(
      `  KEYNV_JWT_SECRET         ${jwtSecret.slice(0, 8)}... (base64, 48 bytes)\n`,
    );
    this.context.stdout.write(
      `  KEYNV_MASTER_KEY         ${masterKey.slice(0, 8)}... (base64, 32 bytes)\n`,
    );
    this.context.stdout.write(
      `  KEYNV_WEB_SESSION_SECRET ${webSessionSecret.slice(0, 8)}... (base64, 48 bytes)\n`,
    );
    this.context.stdout.write('\nNext steps:\n');
    this.context.stdout.write(`  1. Feed ${outPath} into your deployment:\n`);
    this.context.stdout.write('     docker compose --env-file .keynv-server.env up -d\n');
    this.context.stdout.write('     or load it into Coolify as environment variables.\n');
    this.context.stdout.write('  2. Bootstrap the first owner:\n');
    this.context.stdout.write(
      '     docker exec -it <server-container> node dist/bootstrap.js \\\n',
    );
    this.context.stdout.write('       --owner-email alice@example.com \\\n');
    this.context.stdout.write('       --owner-password "<a long random password>" \\\n');
    this.context.stdout.write('       --org-name "Acme Inc"\n');
    this.context.stdout.write('  3. Install the CLI and log in:\n');
    this.context.stdout.write('     npm install -g @keynv/cli\n');
    this.context.stdout.write('     keynv login --server https://keynv.example.com\n');
    this.context.stdout.write('  4. Onboard your first project:\n');
    this.context.stdout.write('     cd your-project && keynv init\n');

    if (this.compose) {
      const composeContent = `# keynv server + Litestream sidecar
# Generated by \`keynv server init\`.
# Load with: docker compose --env-file .keynv-server.env up -d

services:
  server:
    image: ghcr.io/keynv-labs/keynv-server:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .keynv-server.env
    volumes:
      - keynv-data:/data

  litestream:
    image: litestream/litestream:latest
    restart: unless-stopped
    volumes:
      - keynv-data:/data
    command: replicate
    environment:
      LITESTREAM_DB_PATH: /data/keynv.db
      LITESTREAM_REPLICA_URL: s3://your-bucket/keynv
      AWS_ACCESS_KEY_ID: \${LITESTREAM_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: \${LITESTREAM_AWS_SECRET_ACCESS_KEY}

volumes:
  keynv-data:
`;

      writeFileSync('docker-compose.yml', composeContent, { mode: 0o600 });
      this.context.stdout.write(
        '\nWrote docker-compose.yml (update Litestream S3 config before deploying).\n',
      );
    }

    return 0;
  }
}
