/**
 * AI-context markdown that the keynv setup flow writes into a project's
 * `AGENTS.md`. The goal is for any AI coding agent that indexes the
 * repo (Claude Code, Cursor, Aider, Codex, Copilot CLI, etc.) to
 * pick up the keynv mental model and start suggesting `keynv exec`
 * and `keynv secret create` instead of writing `.env` files.
 *
 * The block is wrapped in HTML-comment markers so re-running setup updates
 * only this section without touching the user's other AGENTS.md content.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const AGENTS_FILE_BASENAME = 'AGENTS.md';
export const KEYNV_BLOCK_START =
  '<!-- keynv:start -- generated by keynv setup; safe to leave intact, will be refreshed on re-run -->';
export const KEYNV_BLOCK_END = '<!-- keynv:end -->';

/**
 * The body that lives between the markers. Re-renders cheaply if we
 * ever templatize it (right now it's static).
 */
export function aiContextBody(): string {
  return `## keynv (secrets)

This project uses [keynv](https://keynv.dev) for secrets. \`.keynv.env\` files contain **alias references** like \`OPENAI_API_KEY=@projectname.dev.openai-key\` — these are NOT real values, they are references to secrets stored in the keynv vault.

In a monorepo, expect **one \`.keynv.env\` per app directory** (e.g. \`apps/api/.keynv.env\`, \`apps/web/.keynv.env\`) next to the original \`.env\` file that was migrated. \`keynv exec\` walks upward from the current directory and loads the nearest one, so running it from inside an app's folder picks up that app's aliases.

### Mental model

- **\`.keynv.env\`** — checked into git, contains aliases. Safe to read, edit, commit. May appear in subdirectories of a monorepo.
- **Vault** — holds the real values. The \`keynv\` CLI reads it on demand.
- **\`keynv exec -- <command>\`** — forks the command in a subprocess where the real values are injected into env vars. The parent process (where you, the AI agent, run) NEVER sees the real values.
- **Redactor** — pipes subprocess stdout/stderr through a masker before they reach this terminal. Even if a script accidentally echoes a secret, you see \`<REDACTED:...>\` here.

### What you should do

When the user asks about secrets or env vars, follow this decision tree:

| User intent | Run / suggest |
|---|---|
| "Add a new API key" / "set up a secret" | \`keynv secret create\` (interactive prompt picks project + env + key) |
| "I have a \`.env\`, migrate it" | Run \`keynv\` and choose **Set up this project** |
| "Run the app / dev server / tests" | Run the project's script as usual (e.g. \`npm run dev\`) — setup already wrapped it with keynv. For a one-off command that isn't a package.json script, use \`keynv exec -- <cmd>\`. |
| "Show me the value of X" | Don't reveal it. \`keynv secret get @alias --copy\` puts the value on the clipboard without printing it. Bare \`keynv secret get\` refuses to print in a non-interactive context; \`--reveal\` forces raw stdout — avoid it in agent contexts. |
| "Rotate this key" | \`keynv secret rotate @alias\` |
| "Add a new env var to the project" | Edit \`.keynv.env\` and add \`NAME=@project.env.key\` (after creating the secret with \`keynv secret create\`) |
| "Who has access?" | \`keynv member list <project>\` |

### Hard rules — do not violate

1. **Never print resolved secret values** to the chat, terminal, log, or any file. The user's editor / scrollback / chat history is an attack surface.
2. **Never write a \`.env\` file** (or any file) containing real secret values. The whole point of keynv is that those don't exist on disk.
3. **Never edit \`.keynv.env\` to substitute resolved values for aliases.** The file should only ever contain \`@project.env.key\` references and plain non-secret literals.
4. **Use \`keynv exec --\` to run commands that need env vars.** Don't try to load \`.keynv.env\` yourself by parsing it manually; the wrapper handles resolution + redaction + subprocess isolation.
5. **If a tool fails with "blocked by keynv-guard" or similar**, do NOT try to work around it. Tell the user — that's a sign of a misconfiguration, not an obstacle to bypass.
6. **Treat the alias literal (\`@project.env.key\`) as the canonical reference**, never the resolved value. When you write code, configs, or commands that need a secret, write the alias.

### Quick reference

\`\`\`bash
keynv                       # interactive TUI menu (pick projects, secrets, members)
keynv exec -- <cmd>         # run cmd with .keynv.env loaded
keynv secret create         # walk through creating a new secret
keynv secret list <project> # list aliases (no values)
keynv whoami                # who am I logged in as
keynv --help                # full command list
\`\`\`

If \`.keynv.env\` is missing or empty, the user probably hasn't run setup yet — suggest running \`keynv\` and choosing **Set up this project** before they paste a secret into a \`.env\`.`;
}

/** Full block including markers, ready to splice into AGENTS.md. */
export function renderKeynvBlock(): string {
  return `${KEYNV_BLOCK_START}\n${aiContextBody()}\n${KEYNV_BLOCK_END}`;
}

export type WriteOutcome = 'created' | 'updated' | 'appended' | 'unchanged';

/**
 * Idempotently install the keynv block into AGENTS.md at \`rootPath\`.
 *
 * Behavior:
 * - file missing → create with our block plus a tiny preamble
 * - file exists, has our markers → replace block contents
 * - file exists, no markers → append block at the end
 * - file exists, our block already up-to-date → no-op
 */
export function writeAiContext(rootPath: string): WriteOutcome {
  const path = join(rootPath, AGENTS_FILE_BASENAME);
  const block = renderKeynvBlock();

  if (!existsSync(path)) {
    const initial = `# Agent guidance for this project\n\n${block}\n`;
    writeFileSync(path, initial);
    return 'created';
  }

  const existing = readFileSync(path, 'utf8');
  const startIdx = existing.indexOf(KEYNV_BLOCK_START);
  const endIdx = existing.indexOf(KEYNV_BLOCK_END);

  if (startIdx >= 0 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + KEYNV_BLOCK_END.length);
    const next = `${before}${block}${after}`;
    if (next === existing) return 'unchanged';
    writeFileSync(path, next);
    return 'updated';
  }

  // Append: ensure exactly one blank line of separation.
  const sep =
    existing.length === 0
      ? ''
      : existing.endsWith('\n\n')
        ? ''
        : existing.endsWith('\n')
          ? '\n'
          : '\n\n';
  const trailingNewline = existing.endsWith('\n') ? '' : '\n';
  writeFileSync(path, `${existing}${trailingNewline}${sep}${block}\n`);
  return 'appended';
}
