{{- if and (not .Values.server.existingJwtSecret) .Values.server.jwtSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keynv.jwtSecretName" . }}
  labels:
    {{- include "keynv.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYNV_JWT_SECRET: {{ .Values.server.jwtSecret | quote }}
{{- end -}}
{{- if and .Values.litestream.enabled (not .Values.litestream.existingCredentialsSecret) (or .Values.litestream.accessKeyId .Values.litestream.secretAccessKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keynv.fullname" . }}-litestream
  labels:
    {{- include "keynv.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.litestream.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.litestream.secretAccessKey | quote }}
{{- end -}}
