/**
 * Shell-history hook scripts.
 *
 * Pure-shell implementations (no node / keynv subprocess per command)
 * to keep prompt latency at ~microseconds. The regex bank is a hand-
 * mirrored *subset* of `@keynv/redactor`'s `BUILTIN_PATTERNS`, in
 * POSIX ERE / sed-compatible syntax. **Update both banks together** —
 * a TODO marker lives at the top of each template referencing the
 * canonical patterns file.
 *
 * Why a subset:
 *   - Multi-line patterns (PEM blocks) can't appear on a single shell
 *     command line; omitted.
 *   - Entropy detection isn't viable in pure shell; omitted. The
 *     watcher daemon (Phase A Step 4) catches anything regex misses.
 *
 * Why ERE (not PCRE):
 *   - `sed -E` is POSIX; available on macOS, Linux, BSD.
 *   - We use `|` as the sed delimiter to avoid escaping `/` in URIs.
 *   - No `\b` word boundaries — POSIX ERE doesn't have them. Acceptable:
 *     false positives on secret-shaped substrings inside larger
 *     tokens are *still secret-shaped substrings*.
 */

/**
 * Canonical POSIX ERE regex. Embedded as a single string into each
 * shell template. Kept in one place to make pattern updates atomic.
 *
 * Order matters: longer / more-specific alternatives first so the
 * sed substitution catches the canonical form.
 *
 * Pattern bank mirror, last synced against `packages/redactor/src/patterns.ts`:
 *   - aws-access-key-id           (AKIA|ASIA)[0-9A-Z]{16}
 *   - gcp-api-key                 AIza[0-9A-Za-z_-]{35}
 *   - github-pat (classic/oauth)  gh[uops]_[A-Za-z0-9]{36}
 *   - github-pat-fine-grained     github_pat_[A-Za-z0-9_]{40,}
 *   - slack-bot/user-token        xox[abp]-[A-Za-z0-9-]{24,}
 *   - stripe (sk|rk)_(live|test)  (sk|rk)_(live|test)_[A-Za-z0-9]{24,}
 *   - anthropic-api-key           sk-ant-(api03|admin01)-[A-Za-z0-9_-]{20,}
 *   - openai-api-key              sk-(proj-)?[A-Za-z0-9_-]{20,}
 *   - jwt                         eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}
 *   - postgres/mysql/mongodb URI  with @ credentials
 *   - redis URI with @ credentials
 */
export const SHELL_SECRET_ERE =
  '(AKIA|ASIA)[0-9A-Z]{16}' +
  '|AIza[0-9A-Za-z_-]{35}' +
  '|gh[uops]_[A-Za-z0-9]{36}' +
  '|github_pat_[A-Za-z0-9_]{40,}' +
  '|xox[abp]-[A-Za-z0-9-]{24,}' +
  '|(sk|rk)_(live|test)_[A-Za-z0-9]{24,}' +
  '|sk-ant-(api03|admin01)-[A-Za-z0-9_-]{20,}' +
  '|sk-(proj-)?[A-Za-z0-9_-]{20,}' +
  '|eyJ[A-Za-z0-9_-]{10,}\\.eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}' +
  // URIs use literal-space exclusion rather than [:space:] so the
  // pattern works in BSD sed (macOS) and JS RegExp consistently.
  // Shell commands containing tabs in URIs are vanishingly rare.
  '|(postgresql|postgres|mysql|mongodb)(\\+srv)?://[^@ ]+@[^ ]+' +
  '|rediss?://[^@ ]+@[^ ]+';

const HEADER = (shell: string): string =>
  `# keynv shell history hook (${shell}) — DO NOT EDIT MANUALLY
# Generated by \`keynv shell install\`. Re-run \`keynv shell install\`
# after updating keynv (the pattern bank evolves with the redactor).
# Remove with \`keynv shell uninstall\`.
#
# What it does: matches secret-shaped substrings (vendor-prefixed
# tokens, JWTs, credential-bearing URIs) on each command line you
# enter and replaces them with [REDACTED:keynv] BEFORE the line lands
# in your shell history file.
#
# Pure regex; no subprocess unless a match fires. Pattern bank mirrors
# the canonical bank at @keynv/redactor/src/patterns.ts — update both
# when adding a pattern.
`;

export const ZSH_HOOK = `${HEADER('zsh')}
_keynv_secret_re='${SHELL_SECRET_ERE}'

_keynv_zshaddhistory() {
  emulate -L zsh
  local line="$1"
  if [[ "$line" =~ $_keynv_secret_re ]]; then
    # Delimiter is '#' — '|' would clash with regex alternation in
    # BSD sed (macOS). No keynv pattern or replacement contains '#'.
    local masked
    masked=$(printf '%s' "$line" | sed -E "s#$_keynv_secret_re#[REDACTED:keynv]#g")
    print -sr -- "$masked"
    return 1
  fi
  return 0
}

autoload -Uz add-zsh-hook 2>/dev/null
add-zsh-hook zshaddhistory _keynv_zshaddhistory
`;

export const BASH_HOOK = `${HEADER('bash')}
# Bash has no zshaddhistory equivalent. We hook PROMPT_COMMAND and
# rewrite the most-recent history entry just before the next prompt.
# Small race window: HISTFILE write at shell-exit (or each command if
# histappend + PROMPT_COMMAND ... -a is set) may briefly persist the
# raw value before our rewrite. For the file at rest this is fine;
# concurrent readers of the in-memory history get unredacted text
# until the next prompt.

_keynv_secret_re='${SHELL_SECRET_ERE}'

_keynv_bash_filter() {
  local prev_exit=$?
  local raw
  raw="$(HISTTIMEFORMAT='' history 1 2>/dev/null)" || return $prev_exit
  local hnum="\${raw%% *}"
  local line="\${raw#* }"
  line="\${line# }"
  if [[ "$line" =~ $_keynv_secret_re ]]; then
    # See zsh template re: delimiter choice.
    local masked
    masked=$(printf '%s' "$line" | sed -E "s#$_keynv_secret_re#[REDACTED:keynv]#g")
    history -d "$hnum" 2>/dev/null
    history -s "$masked"
  fi
  return $prev_exit
}

case ";$PROMPT_COMMAND;" in
  *\\;_keynv_bash_filter\\;*) ;;
  *) PROMPT_COMMAND="_keynv_bash_filter\${PROMPT_COMMAND:+; \$PROMPT_COMMAND}" ;;
esac
`;

export const FISH_HOOK = `${HEADER('fish')}
# Fish stores history as YAML records under
# ~/.local/share/fish/fish_history. We can't atomically rewrite a single
# entry, so we **suppress** matched lines rather than redacting them.
# A command containing a secret-shaped value is deleted from history;
# the user loses the command but never the secret.
#
# After Phase A Step 4 (apps/watcher), the fish_history file itself
# will be watched for any pattern-bank matches and rewritten in place
# anyway. This hook is the preventive belt; the watcher is the
# suspenders.

set -g _keynv_secret_re '${SHELL_SECRET_ERE}'

function _keynv_fish_filter --on-event fish_postexec
  set -l line $argv[1]
  if string match -rq -- $_keynv_secret_re "$line"
    builtin history delete --exact --case-sensitive -- "$line" >/dev/null 2>&1
    builtin history save >/dev/null 2>&1
  end
end
`;

export interface ShellTemplate {
  readonly shell: 'zsh' | 'bash' | 'fish';
  readonly rcFile: string; // relative to $HOME
  readonly hookFilename: string; // under ~/.config/keynv/shell/
  readonly hookBody: string;
  readonly sourceLine: (hookPath: string) => string;
}

export const TEMPLATES: ReadonlyArray<ShellTemplate> = [
  {
    shell: 'zsh',
    rcFile: '.zshrc',
    hookFilename: 'keynv-zsh.zsh',
    hookBody: ZSH_HOOK,
    sourceLine: (p) => `[ -f "${p}" ] && source "${p}"`,
  },
  {
    shell: 'bash',
    rcFile: '.bashrc',
    hookFilename: 'keynv-bash.bash',
    hookBody: BASH_HOOK,
    sourceLine: (p) => `[ -f "${p}" ] && source "${p}"`,
  },
  {
    shell: 'fish',
    rcFile: '.config/fish/config.fish',
    hookFilename: 'keynv-fish.fish',
    hookBody: FISH_HOOK,
    sourceLine: (p) => `test -f "${p}"; and source "${p}"`,
  },
];

export const BLOCK_START = '# >>> keynv shell hook >>>';
export const BLOCK_END = '# <<< keynv shell hook <<<';
